default_platform :ios

platform :ios do

PROJECT_NAME = "DevOpsTest";

  lane :beta do
    gym(scheme: "DevOpsTest",
    configuration: "Internal Release",
    export_method: 'ad-hoc',
    export_options: {
      use_automatic_signing: 'true',
        export_xcargs: "-allowProvisioningUpdates"
      })
  end

end
